dbfilename redis_queue.rdb
dir /mnt/d/works/soleappos/config/pids
pidfile /mnt/d/works/soleappos/config/pids/redis_queue.pid
bind 127.0.0.1
port 6381

aclfile /mnt/d/works/soleappos/config/redis_queue.acl
