dbfilename redis_queue.rdb
dir /home/frappe-user/frappe-bench-15/config/pids
pidfile /home/frappe-user/frappe-bench-15/config/pids/redis_queue.pid
bind 127.0.0.1
port 6381

aclfile /home/frappe-user/frappe-bench-15/config/redis_queue.acl
