dbfilename redis_cache.rdb
dir /home/frappe-user/frappe-bench-15/config/pids
pidfile /home/frappe-user/frappe-bench-15/config/pids/redis_cache.pid
bind 127.0.0.1
port 6380
maxmemory 788mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/frappe-user/frappe-bench-15/config/redis_cache.acl
