dbfilename redis_cache.rdb
dir /mnt/d/works/soleappos/config/pids
pidfile /mnt/d/works/soleappos/config/pids/redis_cache.pid
bind 127.0.0.1
port 6380
maxmemory 788mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /mnt/d/works/soleappos/config/redis_queue.acl
